---
micronaut:
  application:
    name: flyway-test
---
# datasources:
#   default:
#     url: jdbc:mysql://localhost/logsmetrics
#     driverClassName: com.mysql.cj.jdbc.Driver
#     username: amti-dev
#     password: dev

datasources:
  default:
    url: "jdbc:h2:mem:flywayDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
    username: "sa"
    password: ""
    driverClassName: "org.h2.Driver"
jpa:
  default:
    packages-to-scan:
      - "example.micronaut"
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
flyway:
  datasources:
    default:
      locations: classpath:databasemigrations
